### ISSUE TITLE
wrong vad labeling ?

### ISSUE THREAD

**Issue by kfmn** [fgnt/libriwasn#1]
Hi,

I have downloaded LibriWASN dataset and started from checking VAD labeling of the very first session `libriwasn_200/0L/overlap_ratio_0.0_sil2.9_3.0_session0_actual0.0`

I am observing the most early segments in speaker.csv are related to the speaker 7 and have following bounds 
12544,38144
47104,60928 
Division by samplerate of 16000 provides the following bounds in seconds:
from 0.784 to 2.384
from 2.944 to 3.808
But when looking into Nexus_ntlab_asn_ID_0.wav I see the first utterance is from about 0.8 till 3.6 seconds without any notable pauses inside... And next segments of speaker 7 looks strange too...

Maybe I treat info from speaker.csv wrongly ? 

Best regards, 
Maxim.

**Comment by schmalen** [comment]
I will take a look at it. I remember that the vad was quite aggressive and sometimes it detected a speech pause although the speech was active.

**Comment by schmalen** [comment]
There was a strange error in the VAD estimation process resulting in missed activities. Thank you for pointing us to this issue.

I created a new version of LibriWASN and uploaded it to Zenodo (https://zenodo.org/records/10952434). Download scripts, md5sum checks and more have been updated. Checking the annotations, the vad now seems to fit.

Best regards
Jörg
